---
abstract: "Deal with a \"stack\" of messages"
author:
  - 'Cory G Watson, C<< <gphat at cpan.org> >>'
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Message-Stack
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.90
  MooseX::Aliases: 0
  MooseX::Storage: 0.21
  MooseX::Types: 0.21
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
